-- AlterTable
ALTER TABLE `admin_actions` MODIFY `actionType` ENUM('SUSPEND_JOB', 'DELETE_JOB', 'UNSUSPEND_JOB', 'SUSPEND_EMPLOYER', 'WARN_EMPLOYER', 'DELETE_EMPLOYER', 'RESOLVE_REPORT', 'DISMISS_REPORT', 'APPROVE_COMPANY', 'REJECT_COMPANY') NOT NULL;
