-- AlterTable
ALTER TABLE `subscriptions` MODIFY `planType` ENUM('FREE', 'PRO', 'MAX') NOT NULL DEFAULT 'FREE',
    MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'CANCELLED', 'PAST_DUE') NOT NULL DEFAULT 'INACTIVE';
