-- AlterTable
ALTER TABLE `jobs` ADD COLUMN `isSuspended` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `suspendedAt` DATETIME(3) NULL,
    ADD COLUMN `suspendedBy` INTEGER NULL,
    ADD COLUMN `suspensionReason` TEXT NULL;

-- AlterTable
ALTER TABLE `reports` MODIFY `status` ENUM('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', 'PENDING_EMPLOYER_RESPONSE') NOT NULL DEFAULT 'PENDING';

-- CreateTable
CREATE TABLE `admin_actions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `adminEmail` VARCHAR(191) NOT NULL,
    `actionType` ENUM('SUSPEND_JOB', 'DELETE_JOB', 'UNSUSPEND_JOB', 'SUSPEND_EMPLOYER', 'WARN_EMPLOYER', 'DELETE_EMPLOYER', 'RESOLVE_REPORT', 'DISMISS_REPORT') NOT NULL,
    `targetType` VARCHAR(191) NOT NULL,
    `targetId` INTEGER NOT NULL,
    `reason` TEXT NULL,
    `notes` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `jobs` ADD CONSTRAINT `jobs_suspendedBy_fkey` FOREIGN KEY (`suspendedBy`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
